Keyword Extraction Using KeyBERT.

Install the relevant packages.

In [1]:
from keybert import KeyBERT

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

WARNING:tensorflow:From c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

KeyBert starts by embedding a document into a vector by turning a chunk of text into a fixed sized vector which represents the semnatics of the document.
Extracts key words using simple techniques - count vectorizer, TFADF vectorizer
Embeds each word using the same model used to embed the document, leaving a list of keyword embeddings. 
Similarity measures will be calculated between document and keyword embeddings. This results in a vector, where each value is a similarity measure between the two. Sorts results in decreasing order to get the most simliar words. 

Adding diversity in the data:
Sometimes there is some redundancy in the data, and repetition. 
Max Sum Similarity
Maximal Marginal Relevance

In [2]:
model = KeyBERT(model = "distilbert-base-nli-mean-tokens")

One document PER Coordinate is needed for analysis

In [3]:
import pandas as pd

In [7]:
all_feedback = pd.read_csv('C:\\Users\\User\\Documents\\GitHub\\proutectapp\\csv-json-files\\joinedfeedback.csv')
ratings = all_feedback.loc[:, ['Latitude', 'Longitude', 'q1', 'q2', 'q3', 'q4']]
responses =  all_feedback.loc[:, ['Latitude', 'Longitude', 'responseList']]

responses

      Latitude  Longitude                                       responseList
0    52.285500  -1.558030  The route was busy with the public, but there ...
1    52.286880  -1.533620  There was a long, isolated road with a lack of...
2    52.279250  -1.544650  There was a long, isolated road with a lack of...
3    52.290777  -1.533494  The route was busy with the public as there we...
4    52.275950  -1.516430  Well-lit street, was quite busy with other mem...
..         ...        ...                                                ...
779  52.292370  -1.548190  A really nice walk to do in the evening.; The ...
780  52.285970  -1.536280  The route felt fairly safe with some street li...
781  52.282960  -1.545510  The route felt fairly safe with some street li...
782  52.288400  -1.538270  Walking through the park made me feel uneasy a...
783  52.289680  -1.542560  I don't enjoy walking by the park at night - t...

[784 rows x 3 columns]

Need to classify each coordinate to be safe/unsafe utilising user feedback. Used average of all answers to question 1 "How safe did you feel on the route?"

In [26]:
classification_list = []
for index, row in ratings.iterrows():
    if row["q1"] > 2.5:
        classification_list.append("safe")
    else:
        classification_list.append("unsafe")

ratings["Classification"] = classification_list

ratings
ratings["Classification"].value_counts()

Classification
safe      413
unsafe    371
Name: count, dtype: int64

In [61]:
ratings['q2'] = ratings['q2'] / 5
ratings['q3'] = ratings['q3'] / 5
ratings['q4'] = ratings['q4'] / 5

In [62]:
ratings

      Latitude  Longitude   q1     q2     q3     q4 Classification
0    52.285500  -1.558030  3.0  0.192  0.032  0.008           safe
1    52.286880  -1.533620  3.0  0.184  0.016  0.008           safe
2    52.279250  -1.544650  3.0  0.184  0.016  0.008           safe
3    52.290777  -1.533494  3.5  0.190  0.032  0.014           safe
4    52.275950  -1.516430  3.0  0.184  0.024  0.008           safe
..         ...        ...  ...    ...    ...    ...            ...
779  52.292370  -1.548190  3.0  0.182  0.026  0.016           safe
780  52.285970  -1.536280  2.5  0.176  0.012  0.008         unsafe
781  52.282960  -1.545510  2.5  0.176  0.012  0.008         unsafe
782  52.288400  -1.538270  2.0  0.176  0.008  0.008         unsafe
783  52.289680  -1.542560  2.0  0.176  0.024  0.016         unsafe

[784 rows x 7 columns]

In [63]:
keywords_list = []

for index, row in responses.iterrows():
  
    doc = row["responseList"]

    keywords = model.extract_keywords(doc, keyphrase_ngram_range=(1,2), stop_words='english', use_mmr=True, diversity=0.9)

    keywords_list.append(keywords)

responses['Key words'] = keywords_list

In [64]:
keywords_list = []

for index, row in responses.iterrows():
  
    doc = row["responseList"]

    keywords = model.extract_keywords(doc, keyphrase_ngram_range=(1,3), stop_words='english', use_mmr=True, diversity=0.9)

    keywords_list.append(keywords)

responses['Key words 3'] = keywords_list

In [65]:
responses

,Latitude,Longitude,responseList,Key words,Key words 2,Key words 3
0,52.285500,-1.558030,"The route was busy with the public, but there ...","[(busy public, 0.5604), (lot cars, 0.3592), (u...","[(busy, 0.3785), (unsafe, 0.3211), (cars, 0.31...","[(cars feel unsafe, 0.7099), (busy public, 0.5..."
1,52.286880,-1.533620,"There was a long, isolated road with a lack of...","[(isolated road, 0.7717), (long isolated, 0.65...","[(isolated, 0.57), (road, 0.5312), (long, 0.45...","[(long isolated road, 0.8514), (lack lighting ..."
2,52.279250,-1.544650,"There was a long, isolated road with a lack of...","[(isolated road, 0.7717), (long isolated, 0.65...","[(isolated, 0.57), (road, 0.5312), (long, 0.45...","[(long isolated road, 0.8514), (lack lighting ..."
3,52.290777,-1.533494,The route was busy with the public as there we...,"[(parade safer, 0.4993), (shops needed, 0.3651...","[(parade, 0.3846), (shops, 0.2816), (nearby, 0...","[(busy public shops, 0.5989), (parade, 0.3846)..."
4,52.275950,-1.516430,"Well-lit street, was quite busy with other mem...","[(lit street, 0.7497), (busy members, 0.6292),...","[(street, 0.5627), (public, 0.5542), (busy, 0....","[(public lit street, 0.7701), (street quite bu..."
...,...,...,...,...,...,...
779,52.292370,-1.548190,A really nice walk to do in the evening.; The ...,"[(night drunk, 0.5259), (short sweet, 0.2917),...","[(drunk, 0.3404), (short, 0.2023), (12am, 0.13...","[(park night drunk, 0.5805), (poorly lit 12am,..."
780,52.285970,-1.536280,The route felt fairly safe with some street li...,"[(felt helpless, 0.381), (night route, 0.3066)...","[(helpless, 0.3453), (night, 0.2396), (park, 0...","[(park felt helpless, 0.581), (night route, 0...."
781,52.282960,-1.545510,The route felt fairly safe with some street li...,"[(felt helpless, 0.381), (night route, 0.3066)...","[(helpless, 0.3453), (night, 0.2396), (park, 0...","[(park felt helpless, 0.581), (night route, 0...."
782,52.288400,-1.538270,Walking through the park made me feel uneasy a...,"[(uneasy lighting, 0.5117), (walking park, 0.4...","[(uneasy, 0.404), (walking, 0.3186), (park, 0....","[(park feel uneasy, 0.6819), (uneasy lighting,..."
783,52.289680,-1.542560,I don't enjoy walking by the park at night - t...,"[(night drunk, 0.6594), (park night, 0.4406), ...","[(drunk, 0.526), (night, 0.3774), (park, 0.132...","[(park night drunk, 0.7046), (walking park nig..."

In [66]:
combined_df = pd.merge(ratings, responses, on=["Latitude", "Longitude"])

In [67]:
combined_df

,Latitude,Longitude,q1,q2,q3,q4,Classification,responseList,Key words,Key words 2,Key words 3
0,52.285500,-1.558030,3.0,0.192,0.032,0.008,safe,"The route was busy with the public, but there ...","[(busy public, 0.5604), (lot cars, 0.3592), (u...","[(busy, 0.3785), (unsafe, 0.3211), (cars, 0.31...","[(cars feel unsafe, 0.7099), (busy public, 0.5..."
1,52.286880,-1.533620,3.0,0.184,0.016,0.008,safe,"There was a long, isolated road with a lack of...","[(isolated road, 0.7717), (long isolated, 0.65...","[(isolated, 0.57), (road, 0.5312), (long, 0.45...","[(long isolated road, 0.8514), (lack lighting ..."
2,52.279250,-1.544650,3.0,0.184,0.016,0.008,safe,"There was a long, isolated road with a lack of...","[(isolated road, 0.7717), (long isolated, 0.65...","[(isolated, 0.57), (road, 0.5312), (long, 0.45...","[(long isolated road, 0.8514), (lack lighting ..."
3,52.290777,-1.533494,3.5,0.190,0.032,0.014,safe,The route was busy with the public as there we...,"[(parade safer, 0.4993), (shops needed, 0.3651...","[(parade, 0.3846), (shops, 0.2816), (nearby, 0...","[(busy public shops, 0.5989), (parade, 0.3846)..."
4,52.275950,-1.516430,3.0,0.184,0.024,0.008,safe,"Well-lit street, was quite busy with other mem...","[(lit street, 0.7497), (busy members, 0.6292),...","[(street, 0.5627), (public, 0.5542), (busy, 0....","[(public lit street, 0.7701), (street quite bu..."
...,...,...,...,...,...,...,...,...,...,...,...
779,52.292370,-1.548190,3.0,0.182,0.026,0.016,safe,A really nice walk to do in the evening.; The ...,"[(night drunk, 0.5259), (short sweet, 0.2917),...","[(drunk, 0.3404), (short, 0.2023), (12am, 0.13...","[(park night drunk, 0.5805), (poorly lit 12am,..."
780,52.285970,-1.536280,2.5,0.176,0.012,0.008,unsafe,The route felt fairly safe with some street li...,"[(felt helpless, 0.381), (night route, 0.3066)...","[(helpless, 0.3453), (night, 0.2396), (park, 0...","[(park felt helpless, 0.581), (night route, 0...."
781,52.282960,-1.545510,2.5,0.176,0.012,0.008,unsafe,The route felt fairly safe with some street li...,"[(felt helpless, 0.381), (night route, 0.3066)...","[(helpless, 0.3453), (night, 0.2396), (park, 0...","[(park felt helpless, 0.581), (night route, 0...."
782,52.288400,-1.538270,2.0,0.176,0.008,0.008,unsafe,Walking through the park made me feel uneasy a...,"[(uneasy lighting, 0.5117), (walking park, 0.4...","[(uneasy, 0.404), (walking, 0.3186), (park, 0....","[(park feel uneasy, 0.6819), (uneasy lighting,..."
783,52.289680,-1.542560,2.0,0.176,0.024,0.016,unsafe,I don't enjoy walking by the park at night - t...,"[(night drunk, 0.6594), (park night, 0.4406), ...","[(drunk, 0.526), (night, 0.3774), (park, 0.132...","[(park night drunk, 0.7046), (walking park nig..."

In [68]:
from collections import Counter

In [69]:
safe_keywords = combined_df[combined_df["Classification"] == "safe"]["Key words 3"].explode()
unsafe_keywords = combined_df[combined_df["Classification"] == "unsafe"]["Key words 3"].explode()

print(safe_keywords)

print(unsafe_keywords)

safe_word_count = Counter(safe_keywords)
unsafe_word_count = Counter(unsafe_keywords)

top_safe_words = [keyword for keyword, count in safe_word_count.most_common(10)]
top_unsafe_words = [keyword for keyword, count in unsafe_word_count.most_common(10)]

0      (cars feel unsafe, 0.7099)
0           (busy public, 0.5604)
0              (lot cars, 0.3592)
0                (unsafe, 0.3211)
0           (times route, 0.0321)
                  ...
779    (park night drunk, 0.5805)
779      (poorly lit 12am, 0.564)
779      (12am don enjoy, 0.2233)
779             (walking, 0.0672)
779                  (park, 0.06)
Name: Key words 3, Length: 2065, dtype: object
6      (unsafe residential access, 0.7517)
6           (street lighting felt, 0.3424)
6                    (road street, 0.3144)
6                    (residential, 0.2465)
6                  (access public, 0.1257)
                      ...
783             (park night drunk, 0.7046)
783           (walking park night, 0.5303)
783                  (people dark, 0.4086)
783                          (park, 0.132)
783                       (walking, 0.118)
Name: Key words 3, Length: 1855, dtype: object

In [70]:
print(top_safe_words)

print(top_unsafe_words)

[('cars feel unsafe', 0.7099), ('busy public', 0.5604), ('lot cars', 0.3592), ('unsafe', 0.3211), ('times route', 0.0321), ('walk park nice', 0.7759), ('daytime felt safe', 0.6322), ('park', 0.4643), ('busy daytime', 0.3986), ('route', 0.0843)]
[('park felt helpless', 0.581), ('night route', 0.3066), ('street lighting time', 0.2877), ('felt fairly safe', 0.2228), ('park', 0.1952), ('away shops public', 0.5348), ('overall preferred busy', 0.3259), ('hospital nearby', 0.2667), ('safe', 0.2519), ('spaces hospital', 0.2223)]

following code is to alter safety score based on presence of words:

In [71]:
# def adjust_safety_score(row, pos_keywords, neg_keywords, adjustment_factor=0.1):
#     # Assuming the initial safety score is in a column named 'safety_score'
#     initial_score = row['safety_score']
#     keywords = row['keywords_list']
    
#     # Check for the presence of top positive/negative keywords
#     pos_presence = any(keyword in keywords for keyword in pos_keywords)
#     neg_presence = any(keyword in keywords for keyword in neg_keywords)
    
#     # Adjust the score based on keyword presence
#     if pos_presence:
#         return initial_score * (1 + adjustment_factor)  # Increase by adjustment_factor
#     elif neg_presence:
#         return initial_score * (1 - adjustment_factor)  # Decrease by adjustment_factor
#     else:
#         return initial_score  # No change

# # Apply the adjustment function to each row
# joinedfeedback['adjusted_safety_score'] = joinedfeedback.apply(adjust_safety_score, args=(top_positive_keywords, top_negative_keywords), axis=1)

Getting crime data for this dataframe - creating new safety scores.

In [86]:
crime_severity_scores = {
    "Drugs" : 2,
    "Shoplifting" : 2,
    "Burglary" : 5,
    "Theft from the person" : 8,
    "Possession of weapons" : 9,
    "Violence and sexual offences" : 10,
    "Criminal damage and arson" : 7,
    "Vehicle crime" : 4,
    "Bicycle theft " : 2,
    "Other theft" : 1,
    "Public order" : 1,
    "Robbery" : 5, 
    "Anti-social behaviour" : 5,
    "Other crime" : 1
}

In [87]:
import numpy as np

In [88]:
def get_lat_lon_ranges(lat, lon, radius):
    # Earth's radius in meters
    EARTH_RADIUS = 6378137

    # Convert latitude and longitude from degrees to radians
    lat_rad = np.radians(lat)

    # Calculate deltas
    dLat = radius/EARTH_RADIUS
    dLon = radius/(EARTH_RADIUS * np.cos(lat_rad))

    # Convert deltas from radians to degrees
    dLat_deg = np.degrees(dLat)
    dLon_deg = np.degrees(dLon)

    # Define ranges
    lat_range = (lat - dLat_deg, lat + dLat_deg)
    lon_range = (lon - dLon_deg, lon + dLon_deg)

    return lat_range, lon_range

In [89]:
def get_crimes_in_range(all_crime_data, long_min, long_max, lat_min, lat_max, crime_severity_scores):
    # Filter the data to only include crimes within the specified ranges
    crimes_in_range = all_crime_data[
        (all_crime_data['Longitude'] >= long_min) & 
        (all_crime_data['Longitude'] <= long_max) & 
        (all_crime_data['Latitude'] >= lat_min) & 
        (all_crime_data['Latitude'] <= lat_max)
    ]

    crimes_in_range = crimes_in_range.copy()
    
    # Add severity score for each crime
    crimes_in_range['Severity Score'] = crimes_in_range['Crime type'].map(crime_severity_scores)
    # print(crimes_in_range)
    # Calculate average severity score for the crimes in the range
    
    if not crimes_in_range.empty:
        average_severity_score = crimes_in_range['Severity Score'].mean()
        print(average_severity_score)
    else:
        average_severity_score = 0

    return len(crimes_in_range), average_severity_score

In [90]:
crime_data_2021 = pd.read_csv("C:\\Users\\User\\Documents\\GitHub\\proutectapp\\csv-json-files\\crimes_in_range_2021.csv")
crime_data_2022 = pd.read_csv("C:\\Users\\User\\Documents\\GitHub\\proutectapp\\csv-json-files\\crimes_in_range_2022.csv")
crime_data_2023 = pd.read_csv("C:\\Users\\User\\Documents\\GitHub\\proutectapp\\csv-json-files\\crimes_in_range_2023.csv")

In [98]:
def get_coords(dataframe):
    all_locations = [f"{row['Latitude']}, {row['Longitude']}" for index, row in dataframe.iterrows()]
    return [(float(lat), float(lon)) for lat, lon in (s.split(', ') for s in all_locations)]

coords21 = get_coords(crime_data_2021)
coords22 = get_coords(crime_data_2022)
coords23 = get_coords(crime_data_2023)

In [104]:
# Gets a dictionary of all crimes, public space data for each coordinate in a 350m radius 
def create_dict(all_crime_data, all_coordinates, crime_severity_scores):
    coordinate_dict = {}
    for each in all_coordinates:
        coordinate_dict[each] = [0, 0]
        # Gets lat/lon range within a 50m radius
        lat_range, lon_range = get_lat_lon_ranges(each[0], each[1], 50)
        coordinate_dict[each][0], coordinate_dict[each][1] = get_crimes_in_range(all_crime_data, lon_range[0], lon_range[1], lat_range[0], lat_range[1], crime_severity_scores)
    return coordinate_dict

In [105]:
data_2021 = create_dict(crime_data_2021, coords21, crime_severity_scores)
data_2022 = create_dict(crime_data_2021, coords22, crime_severity_scores)
data_2023 = create_dict(crime_data_2021, coords23, crime_severity_scores)

5.0
4.5
5.0
3.857142857142857
5.769230769230769
6.532467532467533
5.40625
6.637931034482759
6.637931034482759
5.225806451612903
6.944444444444445
3.3366336633663365
6.231884057971015
8.084745762711865
5.3
6.6
6.029197080291971
5.368421052631579
8.084745762711865
6.231884057971015
5.368421052631579
3.0526315789473686
3.2419354838709675
6.029197080291971
3.2419354838709675
6.029197080291971
3.3366336633663365
6.029197080291971
4.863636363636363
4.863636363636363
6.029197080291971
3.3366336633663365
3.0526315789473686
7.222222222222222
5.368421052631579
4.0
4.92
5.46969696969697
3.2419354838709675
5.368421052631579
6.231884057971015
6.231884057971015
6.026315789473684
3.0526315789473686
5.9523809523809526
6.285714285714286
6.026315789473684
6.285714285714286
6.285714285714286
6.934210526315789
6.934210526315789
5.125
6.934210526315789
5.125
6.934210526315789
6.838709677419355
5.125
6.838709677419355
6.838709677419355
5.7073170731707314
7.0
7.0
7.0
5.7073170731707314
5.2
5.2
5.8
3.1363636363636362
3.1363636363636362
6.142857142857143
6.142857142857143
3.1363636363636362
5.8
6.142857142857143
6.142857142857143
6.142857142857143
6.142857142857143
6.352941176470588
7.0
3.8181818181818183
6.10126582278481
5.222222222222222
6.742857142857143
3.8181818181818183
4.428571428571429
6.6875
7.2592592592592595
7.2592592592592595
7.666666666666667
3.8181818181818183
4.0
7.0
4.0
3.8181818181818183
6.470588235294118
7.2592592592592595
6.666666666666667
7.2592592592592595
7.2592592592592595
6.428571428571429
7.666666666666667
4.428571428571429
6.6875
7.666666666666667
7.2592592592592595
6.111111111111111
6.25
5.642857142857143
5.642857142857143
6.25
5.333333333333333
8.333333333333334
7.7272727272727275
7.363636363636363
5.0
5.0
6.846153846153846
5.666666666666667
5.0
6.3478260869565215
5.913043478260869
5.913043478260869
6.846153846153846
5.913043478260869
5.913043478260869
5.913043478260869
5.860927152317881
5.913043478260869
4.0
6.846153846153846
6.846153846153846
5.913043478260869
7.363636363636363
5.860927152317881
6.846153846153846
6.3478260869565215
6.2105263157894735
6.2105263157894735
6.2105263157894735
6.2105263157894735
6.2105263157894735
7.816901408450704
6.2105263157894735
6.2105263157894735
6.1923076923076925
6.1923076923076925
6.1923076923076925
7.725
6.1923076923076925
6.1923076923076925
6.1923076923076925
6.181818181818182
5.285714285714286
5.285714285714286
6.181818181818182
7.0
7.725
5.285714285714286
7.725
6.181818181818182
7.725
7.725
7.725
5.0
6.25
7.333333333333333
5.2272727272727275
5.2272727272727275
9.333333333333334
5.2272727272727275
6.25
6.222222222222222
6.05
6.05
7.2631578947368425
6.05
6.05
5.333333333333333
5.7
5.454545454545454
5.7
5.823529411764706
5.966101694915254
5.066666666666666
5.966101694915254
5.3
4.368421052631579
5.966101694915254
6.045454545454546
6.181818181818182
5.823529411764706
5.872340425531915
4.4
5.823529411764706
7.3090909090909095
5.405405405405405
5.823529411764706
4.368421052631579
5.222222222222222
7.2631578947368425
7.2631578947368425
7.333333333333333
5.823529411764706
4.368421052631579
6.391304347826087
5.966101694915254
6.391304347826087
5.3
4.368421052631579
5.466666666666667
5.466666666666667
5.466666666666667
5.466666666666667
6.568627450980392
4.625
6.384615384615385
6.568627450980392
3.315068493150685
5.0
5.172413793103448
6.913043478260869
6.913043478260869
6.913043478260869
3.315068493150685
6.818181818181818
6.818181818181818
5.172413793103448
3.315068493150685
3.4166666666666665
3.315068493150685
3.315068493150685
3.315068493150685
2.4651162790697674
3.315068493150685
2.4651162790697674
2.4651162790697674
2.4651162790697674
2.4651162790697674
2.4651162790697674
2.4651162790697674
2.4651162790697674
5.172413793103448
4.428571428571429
4.428571428571429
5.5
6.913043478260869
8.666666666666666
8.666666666666666
8.666666666666666
8.666666666666666
8.666666666666666
5.5
6.913043478260869
6.913043478260869
4.8
4.2631578947368425
4.2631578947368425
4.2631578947368425
6.333333333333333
4.833333333333333
6.0
6.230769230769231
6.333333333333333
5.0
6.230769230769231
6.230769230769231
6.230769230769231
6.230769230769231
7.258064516129032
5.0
5.0
6.866666666666666
5.363636363636363
6.866666666666666
6.166666666666667
7.7368421052631575
7.7368421052631575
7.258064516129032
7.7368421052631575
9.2
7.258064516129032
7.7368421052631575
5.111111111111111
6.233333333333333
3.8181818181818183
6.233333333333333
5.2727272727272725
5.2727272727272725
6.233333333333333
5.2727272727272725
4.466666666666667
5.2727272727272725
4.466666666666667
4.466666666666667
5.2727272727272725
3.8181818181818183
3.8181818181818183
5.2727272727272725
5.2727272727272725
4.466666666666667
6.233333333333333
6.233333333333333
4.2
5.0
5.722222222222222
5.0
6.09375
5.722222222222222
6.09375
4.2
5.0
6.114285714285714
5.923076923076923
4.916666666666667
6.891891891891892
4.3
4.916666666666667
6.733333333333333
6.891891891891892
6.891891891891892
4.916666666666667
6.733333333333333
4.916666666666667
6.3
5.6
6.891891891891892
6.733333333333333
4.916666666666667
8.1
6.891891891891892
5.6571428571428575
8.055555555555555
6.25
6.5
8.0
3.5
5.423076923076923
8.0
3.5
6.666666666666667
3.5
3.5
3.5
5.4
5.6571428571428575
5.6571428571428575
5.4
1.4615384615384615
1.4615384615384615
3.5
3.5
1.4615384615384615
1.4615384615384615
4.0
8.875
8.0
6.25
8.875
3.5
8.875
8.875
6.666666666666667
6.648148148148148
5.172413793103448
5.75
6.157894736842105
6.0
5.172413793103448
6.0
6.157894736842105
6.538461538461538
6.538461538461538
5.823529411764706
5.823529411764706
6.157894736842105
6.538461538461538
6.538461538461538
6.538461538461538
6.157894736842105
6.846153846153846
7.285714285714286
5.333333333333333
7.59375
7.59375
7.59375
9.0
9.0
7.59375
9.0
10.0
3.857142857142857
3.857142857142857
3.857142857142857
6.637931034482759
6.637931034482759
6.704545454545454
6.637931034482759
7.222222222222222
3.3366336633663365
3.3366336633663365
4.863636363636363
5.225806451612903
6.231884057971015
4.92
3.3366336633663365
3.3366336633663365
3.4
3.3366336633663365
3.2419354838709675
6.045454545454546
6.029197080291971
6.083333333333333
5.225806451612903
3.2419354838709675
6.0
5.225806451612903
3.2419354838709675
4.863636363636363
4.1
3.2419354838709675
3.3366336633663365
3.3366336633663365
3.3366336633663365
3.3366336633663365
3.3366336633663365
6.029197080291971
4.863636363636363
5.3
6.231884057971015
6.029197080291971
3.3366336633663365
7.1
6.029197080291971
6.026315789473684
5.9523809523809526
3.0526315789473686
5.9523809523809526
4.384615384615385
6.026315789473684
6.934210526315789
5.125
6.7407407407407405
6.934210526315789
6.7407407407407405
6.7407407407407405
6.838709677419355
7.6
6.838709677419355
6.838709677419355
6.838709677419355
6.838709677419355
6.916666666666667
6.916666666666667
5.7073170731707314
6.666666666666667
6.666666666666667
6.571428571428571
4.333333333333333
3.1363636363636362
5.0
5.2
5.166666666666667
5.5
5.428571428571429
3.1363636363636362
3.1363636363636362
6.142857142857143
5.8
4.428571428571429
6.666666666666667
3.8181818181818183
5.222222222222222
5.857142857142857
6.742857142857143
5.222222222222222
5.222222222222222
6.428571428571429
7.220588235294118
6.352941176470588
7.2592592592592595
7.2592592592592595
6.6
6.578947368421052
7.2592592592592595
8.818181818181818
7.2592592592592595
7.2592592592592595
6.6
7.2592592592592595
7.088888888888889
5.166666666666667
3.6
8.2
6.111111111111111
3.5
6.153846153846154
6.571428571428571
4.857142857142857
4.5
5.333333333333333
6.153846153846154
6.153846153846154
5.333333333333333
3.3333333333333335
6.153846153846154
5.666666666666667
5.0
5.0
6.846153846153846
8.375
5.833333333333333
7.2
6.5
5.0
5.913043478260869
5.860927152317881
6.846153846153846
6.846153846153846
5.913043478260869
6.846153846153846
3.8333333333333335
6.846153846153846
6.846153846153846
5.913043478260869
5.913043478260869
6.846153846153846
5.860927152317881
6.846153846153846
6.944444444444445
6.944444444444445
6.846153846153846
6.846153846153846
6.3478260869565215
6.846153846153846
4.466666666666667
6.086956521739131
4.466666666666667
4.466666666666667
6.086956521739131
10.0
7.816901408450704
7.816901408450704
6.086956521739131
7.725
5.285714285714286
5.285714285714286
5.285714285714286
7.725
4.909090909090909
9.166666666666666
5.2272727272727275
5.5
9.166666666666666
7.333333333333333
6.05
6.222222222222222
5.2727272727272725
6.461538461538462
5.2727272727272725
5.2727272727272725
6.461538461538462
5.823529411764706
4.368421052631579
5.3
6.181818181818182
5.823529411764706
5.066666666666666
4.4
5.066666666666666
6.045454545454546
6.391304347826087
5.5
7.2631578947368425
5.823529411764706
5.5
5.066666666666666
5.411764705882353
5.2727272727272725
5.466666666666667
5.9411764705882355
5.466666666666667
5.2727272727272725
5.9411764705882355
3.769230769230769
6.913043478260869
5.5
6.913043478260869
4.111111111111111
8.5
5.172413793103448
3.315068493150685
5.172413793103448
5.172413793103448
6.913043478260869
6.913043478260869
3.0
2.4651162790697674
3.4166666666666665
3.4166666666666665
3.315068493150685
3.315068493150685
3.4166666666666665
3.4166666666666665
5.6
5.5
5.6
3.315068493150685
6.913043478260869
6.0
6.913043478260869
4.2631578947368425
4.2631578947368425
4.833333333333333
6.0
4.2
4.833333333333333
6.0
6.230769230769231
5.0
4.833333333333333
6.230769230769231
4.833333333333333
6.866666666666666
6.166666666666667
5.363636363636363
6.5
6.5
8.0
5.033333333333333
5.111111111111111
6.233333333333333
6.233333333333333
6.233333333333333
5.2727272727272725
6.233333333333333
5.033333333333333
6.233333333333333
6.233333333333333
5.2727272727272725
5.2727272727272725
5.2727272727272725
6.233333333333333
6.233333333333333
5.033333333333333
5.2727272727272725
6.233333333333333
6.305555555555555
6.233333333333333
6.233333333333333
6.233333333333333
6.233333333333333
5.4
3.8181818181818183
5.111111111111111
4.466666666666667
6.111111111111111
6.111111111111111
6.233333333333333
6.233333333333333
6.233333333333333
5.2727272727272725
5.722222222222222
5.923076923076923
5.722222222222222
5.0
6.761904761904762
5.923076923076923
4.2
5.923076923076923
6.09375
6.09375
5.722222222222222
6.891891891891892
8.1
6.891891891891892
8.1
7.636363636363637
6.891891891891892
5.6
6.891891891891892
6.891891891891892
6.891891891891892
6.733333333333333
8.1
6.891891891891892
7.636363636363637
6.3
8.1
8.1
8.1
6.3
6.891891891891892
6.0
5.6571428571428575
6.666666666666667
5.6571428571428575
5.6571428571428575
3.5
1.4615384615384615
8.0
8.0
3.5
3.5
1.4615384615384615
1.4615384615384615
5.423076923076923
1.4615384615384615
3.5
3.5
6.0
3.5
8.0
5.423076923076923
3.5
5.823529411764706
4.857142857142857
5.428571428571429
6.648148148148148
6.0
6.0
6.0
4.857142857142857
5.75
6.0
6.538461538461538
4.857142857142857
5.172413793103448
6.157894736842105
6.105263157894737
6.538461538461538
6.0
4.909090909090909
5.36
5.36
4.4
3.6666666666666665
5.36
4.909090909090909
10.0
10.0
5.36
5.0
7.59375
7.444444444444445
7.59375
7.59375
3.5
6.846153846153846
5.5
10.0
10.0
6.833333333333333
5.40625
6.571428571428571
6.532467532467533
5.40625
6.083333333333333
4.75
4.75
5.46969696969697
5.242857142857143
6.045454545454546
4.863636363636363
6.0
5.368421052631579
6.0
5.368421052631579
6.029197080291971
6.0
7.222222222222222
6.733333333333333
5.76595744680851
4.863636363636363
6.231884057971015
5.3
6.0
5.225806451612903
4.92
3.3366336633663365
3.3366336633663365
3.3366336633663365
3.3366336633663365
3.3366336633663365
3.3366336633663365
6.029197080291971
3.0526315789473686
3.3366336633663365
6.029197080291971
3.2419354838709675
7.1
6.083333333333333
8.084745762711865
6.029197080291971
6.029197080291971
8.084745762711865
4.1
6.029197080291971
3.2419354838709675
7.111111111111111
5.9523809523809526
3.0526315789473686
3.0526315789473686
3.0526315789473686
6.026315789473684
3.0526315789473686
3.0526315789473686
3.0526315789473686
5.2
6.934210526315789
6.934210526315789
6.934210526315789
6.934210526315789
7.75
6.934210526315789
6.934210526315789
5.125
5.0
6.934210526315789
6.934210526315789
6.942857142857143
7.75
5.0
7.818181818181818
6.7407407407407405
6.934210526315789
5.125
6.934210526315789
5.0
6.934210526315789
6.934210526315789
6.934210526315789
7.818181818181818
7.818181818181818
6.934210526315789
6.934210526315789
6.7407407407407405
5.125
5.0
6.666666666666667
6.666666666666667
6.666666666666667
5.7073170731707314
5.7073170731707314
6.571428571428571
6.571428571428571
6.6875
5.333333333333333
6.6875
6.142857142857143
6.592592592592593
5.222222222222222
6.6875
7.666666666666667
5.222222222222222
8.818181818181818
7.666666666666667
6.035714285714286
6.470588235294118
7.088888888888889
4.428571428571429
6.6
6.6875
7.220588235294118
8.818181818181818
6.035714285714286
7.2592592592592595
3.6
8.333333333333334
4.5
6.153846153846154
6.571428571428571
6.25
5.642857142857143
9.1
6.25
5.333333333333333
5.333333333333333
3.9
7.7272727272727275
6.153846153846154
7.7272727272727275
7.7272727272727275
7.7272727272727275
10.0
7.7272727272727275
5.0
6.944444444444445
6.846153846153846
6.846153846153846
5.860927152317881
6.3478260869565215
6.846153846153846
5.0
6.846153846153846
6.846153846153846
6.846153846153846
5.860927152317881
6.846153846153846
5.913043478260869
6.944444444444445
5.860927152317881
5.916666666666667
5.860927152317881
5.860927152317881
5.860927152317881
5.913043478260869
6.846153846153846
5.860927152317881
6.846153846153846
10.0
7.0
6.3478260869565215
6.846153846153846
6.3
6.846153846153846
6.846153846153846
6.846153846153846
5.913043478260869
6.846153846153846
8.5
6.846153846153846
6.846153846153846
6.846153846153846
5.913043478260869
7.363636363636363
6.846153846153846
6.3478260869565215
5.555555555555555
7.777777777777778
4.466666666666667
4.466666666666667
4.466666666666667
7.816901408450704
4.466666666666667
7.816901408450704
6.181818181818182
5.285714285714286
7.0
7.0
6.181818181818182
6.181818181818182
5.2272727272727275
5.2272727272727275
5.2272727272727275
5.2272727272727275
5.833333333333333
10.0
5.833333333333333
5.2272727272727275
7.333333333333333
5.2272727272727275
9.333333333333334
5.7
6.461538461538462
6.222222222222222
6.461538461538462
5.454545454545454
5.454545454545454
6.05
5.823529411764706
6.391304347826087
6.181818181818182
7.3090909090909095
5.7
6.391304347826087
7.3090909090909095
5.5
5.966101694915254
5.222222222222222
5.3
5.7
6.391304347826087
4.4
5.823529411764706
5.872340425531915
7.2631578947368425
7.333333333333333
7.3090909090909095
7.3090909090909095
5.3
6.391304347826087
5.2727272727272725
5.9411764705882355
6.568627450980392
2.8260869565217392
5.6
5.6
6.568627450980392
7.1875
5.9411764705882355
7.816901408450704
6.913043478260869
6.913043478260869
6.913043478260869
5.172413793103448
4.111111111111111
3.315068493150685
3.769230769230769
3.769230769230769
2.4651162790697674
3.315068493150685
2.4651162790697674
2.4651162790697674
6.913043478260869
6.833333333333333
5.172413793103448
6.913043478260869
5.172413793103448
6.818181818181818
7.5
6.913043478260869
6.818181818181818
6.913043478260869
4.2631578947368425
5.0
4.2631578947368425
4.2
6.25
2.5
4.8
6.0
4.833333333333333
8.0
4.75
6.166666666666667
4.75
6.866666666666666
5.363636363636363
6.166666666666667
6.5
7.258064516129032
7.258064516129032
7.258064516129032
7.258064516129032
7.7368421052631575
5.033333333333333
5.2727272727272725
4.466666666666667
5.033333333333333
5.033333333333333
5.033333333333333
6.233333333333333
5.033333333333333
5.033333333333333
5.033333333333333
6.0625
5.2727272727272725
5.033333333333333
6.233333333333333
6.233333333333333
6.233333333333333
6.666666666666667
6.233333333333333
5.2727272727272725
6.233333333333333
5.722222222222222
5.722222222222222
6.285714285714286
5.0
6.114285714285714
5.722222222222222
3.0
5.0
6.09375
5.722222222222222
6.114285714285714
5.0
5.0
5.722222222222222
6.09375
6.761904761904762
7.2
6.114285714285714
5.923076923076923
6.761904761904762
6.761904761904762
4.3
4.3
6.3
8.1
5.6
9.4
7.636363636363637
6.3
6.3
6.891891891891892
7.636363636363637
6.891891891891892
7.333333333333333
8.1
7.444444444444445
5.6
6.733333333333333
6.3
6.25
5.6571428571428575
4.416666666666667
4.416666666666667
8.875
6.666666666666667
6.25
1.4615384615384615
1.4615384615384615
1.4615384615384615
1.4615384615384615
1.4615384615384615
1.4615384615384615
5.423076923076923
8.875
3.5
3.5
4.75
3.5
8.875
8.875
8.875
5.6571428571428575
8.0
5.428571428571429
6.538461538461538
6.2592592592592595
6.648148148148148
4.857142857142857
6.648148148148148
6.648148148148148
5.823529411764706
6.538461538461538
6.538461538461538
5.470588235294118
6.538461538461538
6.538461538461538
6.648148148148148
5.172413793103448
6.157894736842105
5.428571428571429
6.2592592592592595
6.538461538461538
6.0
6.0
6.538461538461538
4.909090909090909
5.36
5.166666666666667
7.59375
7.285714285714286
7.0
5.4
8.0
7.59375
7.59375
7.444444444444445
7.59375
3.5
3.5
1.5
6.846153846153846
6.846153846153846
5.40625
5.40625
6.532467532467533
6.571428571428571
6.571428571428571
5.40625
6.532467532467533
6.704545454545454
8.084745762711865
6.083333333333333
6.029197080291971
4.92
5.242857142857143
6.0
6.029197080291971
6.231884057971015
6.083333333333333
6.029197080291971
5.242857142857143
6.231884057971015
6.029197080291971
4.1
3.2419354838709675
6.231884057971015
6.0227272727272725
3.2419354838709675
3.3366336633663365
6.083333333333333
5.46969696969697
6.231884057971015
4.8
6.029197080291971
4.1
7.222222222222222
8.084745762711865
6.231884057971015
6.029197080291971
3.2419354838709675
5.696969696969697
6.029197080291971
6.231884057971015
4.1
3.2419354838709675
3.3366336633663365
3.3366336633663365
3.3366336633663365
3.3366336633663365
6.029197080291971
6.231884057971015
6.0
3.2419354838709675
3.4
6.231884057971015
5.76595744680851
6.660714285714286
6.231884057971015
6.231884057971015
6.6
6.231884057971015
6.0
6.231884057971015
6.231884057971015
5.5
6.231884057971015
5.242857142857143
6.026315789473684
5.9523809523809526
3.0526315789473686
4.384615384615385
5.9523809523809526
4.384615384615385
5.9523809523809526
5.9523809523809526
7.222222222222222
6.916666666666667
6.838709677419355
6.916666666666667
6.934210526315789
6.838709677419355
6.838709677419355
6.838709677419355
6.838709677419355
6.934210526315789
6.934210526315789
6.838709677419355
6.7407407407407405
7.0
6.333333333333333
6.333333333333333
5.7073170731707314
5.7073170731707314
5.7073170731707314
6.666666666666667
5.7073170731707314
6.0
6.142857142857143
4.333333333333333
6.0
6.125
6.125
6.333333333333333
7.220588235294118
7.0
6.578947368421052
6.035714285714286
7.2592592592592595
6.035714285714286
6.035714285714286
6.035714285714286
6.428571428571429
6.352941176470588
6.352941176470588
6.035714285714286
6.742857142857143
4.0
6.6875
5.222222222222222
6.035714285714286
6.035714285714286
7.088888888888889
7.220588235294118
3.8181818181818183
7.2592592592592595
7.0
7.0
7.0
6.742857142857143
6.352941176470588
7.0
8.818181818181818
6.352941176470588
7.5
6.111111111111111
6.111111111111111
6.111111111111111
7.5
4.857142857142857
6.25
6.25
6.25
6.153846153846154
6.153846153846154
6.153846153846154
6.571428571428571
6.153846153846154
5.642857142857143
5.642857142857143
5.6
4.0
7.7272727272727275
8.333333333333334
10.0
5.111111111111111
5.916666666666667
5.833333333333333
7.363636363636363
6.846153846153846
6.3478260869565215
5.111111111111111
5.0
5.0
5.916666666666667
5.0
5.666666666666667
6.846153846153846
5.913043478260869
5.860927152317881
5.860927152317881
5.913043478260869
5.913043478260869
5.913043478260869
5.860927152317881
5.860927152317881
5.860927152317881
5.555555555555555
7.363636363636363
6.846153846153846
5.916666666666667
6.846153846153846
7.363636363636363
6.846153846153846
7.363636363636363
6.086956521739131
6.769230769230769
6.2105263157894735
6.2105263157894735
6.2105263157894735
6.769230769230769
7.0
6.769230769230769
6.086956521739131
4.466666666666667
4.466666666666667
7.816901408450704
4.466666666666667
4.466666666666667

In [107]:
data_2021

{(52.279611, -1.501874): [9, 5.0],
 (52.272738, -1.498624): [2, 4.5],
 (52.276068, -1.499642): [7, 3.857142857142857],
 (52.294499, -1.530402): [13, 5.769230769230769],
 (52.293096, -1.530358): [79, 6.532467532467533],
 (52.294583, -1.529037): [32, 5.40625],
 (52.292775, -1.530962): [60, 6.637931034482759],
 (52.292862, -1.534759): [31, 5.225806451612903],
 (52.292301, -1.529428): [18, 6.944444444444445],
 (52.291967, -1.535736): [103, 3.3366336633663365],
 (52.288299, -1.535877): [69, 6.231884057971015],
 (52.293131, -1.536853): [59, 8.084745762711865],
 (52.29137, -1.532561): [11, 5.3],
 (52.289332, -1.537743): [5, 6.6],
 (52.292609, -1.536712): [151, 6.029197080291971],
 (52.289063, -1.535854): [23, 5.368421052631579],
 (52.290783, -1.536394): [76, 3.0526315789473686],
 (52.291278, -1.534248): [63, 3.2419354838709675],
 (52.290069, -1.535477): [67, 4.863636363636363],
 (52.289549, -1.531436): [19, 7.222222222222222],
 (52.294878, -1.535383): [1, 4.0],
 (52.289819, -1.535832): [76, 4.92],
 (52.289974, -1.536505): [66, 5.46969696969697],
 (52.291475, -1.534026): [63, 3.2419354838709675],
 (52.292712, -1.53784): [38, 6.026315789473684],
 (52.291106, -1.536258): [76, 3.0526315789473686],
 (52.290478, -1.538904): [22, 5.9523809523809526],
 (52.291944, -1.53905): [14, 6.285714285714286],
 (52.29266, -1.538221): [38, 6.026315789473684],
 (52.291703, -1.539434): [14, 6.285714285714286],
 (52.290591, -1.561642): [77, 6.934210526315789],
 (52.290946, -1.560305): [8, 5.125],
 (52.288778, -1.562291): [31, 6.838709677419355],
 (52.292986, -1.569874): [41, 5.7073170731707314],
 (52.288812, -1.569152): [3, 7.0],
 (52.291014, -1.545071): [5, 5.2],
 (52.291828, -1.548596): [16, 5.8],
 (52.29329, -1.547613): [22, 3.1363636363636362],
 (52.29213, -1.549942): [9, 6.142857142857143],
 (52.291378, -1.548615): [8, 6.142857142857143],
 (52.284801, -1.535576): [17, 6.352941176470588],
 (52.28557, -1.539072): [26, 7.0],
 (52.287521, -1.541412): [11, 3.8181818181818183],
 (52.284969, -1.532701): [80, 6.10126582278481],
 (52.285872, -1.545226): [9, 5.222222222222222],
 (52.286025, -1.533643): [108, 6.742857142857143],
 (52.285958, -1.537162): [15, 4.428571428571429],
 (52.284691, -1.53291): [32, 6.6875],
 (52.286198, -1.541221): [27, 7.2592592592592595],
 (52.286221, -1.533216): [40, 7.666666666666667],
 (52.289896, -1.541813): [7, 4.0],
 (52.285079, -1.533169): [34, 6.470588235294118],
 (52.288876, -1.54087): [3, 6.666666666666667],
 (52.289443, -1.540938): [7, 6.428571428571429],
 (52.292458, -1.541786): [10, 7.666666666666667],
 (52.292737, -1.558484): [9, 6.111111111111111],
 (52.290553, -1.551307): [8, 6.25],
 (52.291531, -1.553349): [14, 5.642857142857143],
 (52.293954, -1.542856): [15, 5.333333333333333],
 (52.294535, -1.546398): [3, 8.333333333333334],
 (52.292418, -1.54318): [11, 7.7272727272727275],
 (52.294286, -1.526518): [33, 7.363636363636363],
 (52.288217, -1.530908): [2, 5.0],
 (52.288889, -1.512721): [12, 5.0],
 (52.292117, -1.528154): [52, 6.846153846153846],
 (52.290407, -1.529947): [6, 5.666666666666667],
 (52.287279, -1.510276): [9, 5.0],
 (52.290094, -1.517195): [25, 6.3478260869565215],
 (52.288822, -1.533951): [139, 5.913043478260869],
 (52.288409, -1.534087): [152, 5.860927152317881],
 (52.29023, -1.530784): [1, 4.0],
 (52.279208, -1.517342): [19, 6.2105263157894735],
 (52.279578, -1.517763): [19, 6.2105263157894735],
 (52.280685, -1.518118): [71, 7.816901408450704],
 (52.281519, -1.515265): [26, 6.1923076923076925],
 (52.283647, -1.514685): [40, 7.725],
 (52.28168, -1.510851): [22, 6.181818181818182],
 (52.281979, -1.515714): [43, 5.285714285714286],
 (52.281319, -1.510327): [22, 6.181818181818182],
 (52.280171, -1.511): [6, 7.0],
 (52.276452, -1.514089): [2, 5.0],
 (52.27683, -1.512033): [4, 6.25],
 (52.278641, -1.510767): [3, 7.333333333333333],
 (52.276181, -1.515836): [44, 5.2272727272727275],
 (52.280861, -1.5085): [12, 9.333333333333334],
 (52.287707, -1.524917): [9, 6.222222222222222],
 (52.285096, -1.52389): [20, 6.05],
 (52.28544, -1.526627): [19, 7.2631578947368425],
 (52.284594, -1.521975): [15, 5.333333333333333],
 (52.283647, -1.521223): [10, 5.7],
 (52.286772, -1.522611): [12, 5.454545454545454],
 (52.284211, -1.531903): [86, 5.823529411764706],
 (52.285288, -1.531481): [60, 5.966101694915254],
 (52.284478, -1.528924): [15, 5.066666666666666],
 (52.285835, -1.53105): [21, 5.3],
 (52.286181, -1.527602): [20, 4.368421052631579],
 (52.283518, -1.529418): [23, 6.045454545454546],
 (52.285399, -1.532198): [23, 6.181818181818182],
 (52.284859, -1.532028): [47, 5.872340425531915],
 (52.287315, -1.528044): [10, 4.4],
 (52.285762, -1.533001): [57, 7.3090909090909095],
 (52.284395, -1.530787): [39, 5.405405405405405],
 (52.28481, -1.526649): [18, 5.222222222222222],
 (52.285827, -1.526828): [19, 7.2631578947368425],
 (52.283267, -1.527369): [15, 7.333333333333333],
 (52.284905, -1.530019): [23, 6.391304347826087],
 (52.282616, -1.524268): [16, 5.466666666666667],
 (52.282213, -1.52008): [53, 6.568627450980392],
 (52.283439, -1.525549): [9, 4.625],
 (52.282777, -1.526245): [13, 6.384615384615385],
 (52.278892, -1.548932): [79, 3.315068493150685],
 (52.275649, -1.547119): [1, 5.0],
 (52.27665, -1.55048): [29, 5.172413793103448],
 (52.271046, -1.55439): [69, 6.913043478260869],
 (52.281383, -1.553818): [11, 6.818181818181818],
 (52.268649, -1.53894): [24, 3.4166666666666665],
 (52.276856, -1.547898): [43, 2.4651162790697674],
 (52.281392, -1.556236): [7, 4.428571428571429],
 (52.269141, -1.542921): [12, 5.5],
 (52.270006, -1.547865): [6, 8.666666666666666],
 (52.269395, -1.543299): [12, 5.5],
 (52.283247, -1.561817): [5, 4.8],
 (52.286722, -1.565697): [57, 4.2631578947368425],
 (52.286919, -1.567851): [6, 6.333333333333333],
 (52.287794, -1.561318): [12, 4.833333333333333],
 (52.288601, -1.560621): [29, 6.0],
 (52.281927, -1.552698): [13, 6.230769230769231],
 (52.283612, -1.553707): [3, 5.0],
 (52.281675, -1.552671): [13, 6.230769230769231],
 (52.279138, -1.53118): [32, 7.258064516129032],
 (52.276546, -1.542038): [2, 5.0],
 (52.28268, -1.535745): [15, 6.866666666666666],
 (52.278365, -1.53368): [23, 5.363636363636363],
 (52.27859, -1.54061): [24, 6.166666666666667],
 (52.284343, -1.538088): [19, 7.7368421052631575],
 (52.278247, -1.535601): [10, 9.2],
 (52.2767, -1.535529): [18, 5.111111111111111],
 (52.278513, -1.532417): [61, 6.233333333333333],
 (52.277174, -1.530233): [12, 3.8181818181818183],
 (52.273768, -1.532922): [33, 5.2727272727272725],
 (52.275298, -1.533331): [15, 4.466666666666667],
 (52.277281, -1.529983): [12, 3.8181818181818183],
 (52.277645, -1.52652): [10, 4.2],
 (52.278234, -1.530046): [22, 5.0],
 (52.279572, -1.527496): [18, 5.722222222222222],
 (52.278986, -1.52932): [23, 5.0],
 (52.280244, -1.529131): [33, 6.09375],
 (52.280359, -1.528602): [33, 6.09375],
 (52.279936, -1.528533): [36, 6.114285714285714],
 (52.276423, -1.526723): [13, 5.923076923076923],
 (52.274318, -1.52424): [12, 4.916666666666667],
 (52.276323, -1.521976): [37, 6.891891891891892],
 (52.278232, -1.522864): [10, 4.3],
 (52.27396, -1.526808): [15, 6.733333333333333],
 (52.275744, -1.525631): [20, 6.3],
 (52.277787, -1.523836): [10, 5.6],
 (52.274602, -1.521012): [30, 8.1],
 (52.280067, -1.543482): [35, 5.6571428571428575],
 (52.28284, -1.537488): [18, 8.055555555555555],
 (52.280957, -1.541113): [12, 6.25],
 (52.281624, -1.541678): [6, 6.5],
 (52.281878, -1.539814): [13, 8.0],
 (52.282569, -1.544322): [52, 3.5],
 (52.282634, -1.547004): [27, 5.423076923076923],
 (52.282019, -1.53905): [6, 6.666666666666667],
 (52.282327, -1.541964): [10, 5.4],
 (52.283876, -1.540556): [39, 1.4615384615384615],
 (52.27964, -1.53777): [1, 4.0],
 (52.281079, -1.537917): [16, 8.875],
 (52.281297, -1.538486): [16, 8.875],
 (52.283542, -1.533332): [54, 6.648148148148148],
 (52.28314, -1.531607): [29, 5.172413793103448],
 (52.282746, -1.534293): [12, 5.75],
 (52.281039, -1.53009): [39, 6.157894736842105],
 (52.280184, -1.534232): [21, 6.0],
 (52.281777, -1.530243): [40, 6.538461538461538],
 (52.283863, -1.532552): [86, 5.823529411764706],
 (52.269466, -1.531677): [13, 6.846153846153846],
 (52.273246, -1.510402): [7, 7.285714285714286],
 (52.273786, -1.512755): [3, 5.333333333333333],
 (52.272952, -1.513248): [32, 7.59375],
 (52.268634, -1.519303): [6, 9.0],
 (52.275507, -1.500909): [3, 10.0],
 (52.275999, -1.5002): [7, 3.857142857142857],
 (52.293421, -1.530677): [44, 6.704545454545454],
 (52.294143, -1.538162): [10, 3.4],
 (52.292912, -1.533849): [23, 6.045454545454546],
 (52.293622, -1.536071): [13, 6.083333333333333],
 (52.289756, -1.533604): [25, 6.0],
 (52.290665, -1.533976): [22, 4.1],
 (52.289354, -1.532142): [21, 7.1],
 (52.292525, -1.533722): [14, 4.384615384615385],
 (52.292271, -1.566186): [27, 6.7407407407407405],
 (52.288653, -1.5626): [31, 6.838709677419355],
 (52.28799, -1.565597): [10, 7.6],
 (52.2889, -1.563829): [12, 6.916666666666667],
 (52.294546, -1.566134): [15, 6.666666666666667],
 (52.294325, -1.567148): [14, 6.571428571428571],
 (52.293635, -1.550865): [6, 4.333333333333333],
 (52.290438, -1.547203): [10, 5.0],
 (52.290989, -1.543121): [6, 5.166666666666667],
 (52.291449, -1.545858): [4, 5.5],
 (52.294128, -1.548367): [7, 5.428571428571429],
 (52.287713, -1.540091): [7, 5.857142857142857],
 (52.286351, -1.534241): [69, 7.220588235294118],
 (52.286822, -1.544439): [5, 6.6],
 (52.285361, -1.534046): [58, 6.578947368421052],
 (52.284732, -1.534023): [22, 8.818181818181818],
 (52.285666, -1.533925): [92, 7.088888888888889],
 (52.292815, -1.55753): [6, 5.166666666666667],
 (52.291066, -1.556433): [5, 3.6],
 (52.29244, -1.556023): [10, 8.2],
 (52.292917, -1.556063): [4, 3.5],
 (52.28754, -1.55122): [13, 6.153846153846154],
 (52.289531, -1.554528): [7, 6.571428571428571],
 (52.289176, -1.548725): [7, 4.857142857142857],
 (52.292375, -1.552974): [6, 4.5],
 (52.292457, -1.546214): [13, 6.153846153846154],
 (52.293499, -1.541233): [3, 3.3333333333333335],
 (52.290931, -1.526129): [8, 8.375],
 (52.291899, -1.525444): [6, 5.833333333333333],
 (52.288958, -1.531985): [5, 7.2],
 (52.294642, -1.521236): [6, 6.5],
 (52.291747, -1.53027): [6, 3.8333333333333335],
 (52.292633, -1.529161): [18, 6.944444444444445],
 (52.279799, -1.514697): [15, 4.466666666666667],
 (52.281007, -1.515344): [24, 6.086956521739131],
 (52.280605, -1.516052): [24, 6.086956521739131],
 (52.278214, -1.518364): [1, 10.0],
 (52.276003, -1.511866): [11, 4.909090909090909],
 (52.275888, -1.51452): [6, 9.166666666666666],
 (52.277161, -1.518171): [2, 5.5],
 (52.283438, -1.522837): [22, 5.2727272727272725],
 (52.285593, -1.5245): [13, 6.461538461538462],
 (52.286174, -1.53046): [21, 5.3],
 (52.284656, -1.530784): [42, 5.5],
 (52.286063, -1.520669): [17, 5.411764705882353],
 (52.283152, -1.523485): [22, 5.2727272727272725],
 (52.282426, -1.52383): [16, 5.466666666666667],
 (52.281804, -1.523441): [17, 5.9411764705882355],
 (52.269099, -1.548226): [13, 3.769230769230769],
 (52.272233, -1.554496): [9, 4.111111111111111],
 (52.2722, -1.55051): [2, 8.5],
 (52.271469, -1.542677): [7, 3.0],
 (52.269489, -1.544514): [5, 5.6],
 (52.279724, -1.569577): [4, 6.0],
 (52.283557, -1.551143): [5, 4.2],
 (52.281181, -1.536464): [12, 6.5],
 (52.277491, -1.535433): [11, 8.0],
 (52.277093, -1.532447): [60, 5.033333333333333],
 (52.27691, -1.536216): [18, 5.111111111111111],
 (52.275615, -1.531539): [36, 6.305555555555555],
 (52.276873, -1.533769): [5, 5.4],
 (52.274294, -1.534074): [9, 6.111111111111111],
 (52.278642, -1.524135): [21, 6.761904761904762],
 (52.274986, -1.520539): [30, 8.1],
 (52.273923, -1.519818): [11, 7.636363636363637],
 (52.282189, -1.536703): [4, 6.0],
 (52.283285, -1.538744): [12, 6.666666666666667],
 (52.282966, -1.528501): [7, 4.857142857142857],
 (52.281545, -1.532899): [14, 5.428571428571429],
 (52.282359, -1.534224): [12, 5.75],
 (52.283405, -1.53046): [20, 6.105263157894737],
 (52.271038, -1.529199): [11, 4.909090909090909],
 (52.272661, -1.525708): [25, 5.36],
 (52.272453, -1.525432): [25, 5.36],
 (52.272533, -1.522984): [5, 4.4],
 (52.269867, -1.52184): [4, 3.6666666666666665],
 (52.269972, -1.523231): [4, 10.0],
 (52.271533, -1.520195): [1, 5.0],
 (52.271797, -1.518844): [18, 7.444444444444445],
 (52.272347, -1.530372): [4, 3.5],
 (52.269772, -1.531806): [13, 6.846153846153846],
 (52.272618, -1.532963): [2, 5.5],
 (52.293873, -1.531361): [6, 6.833333333333333],
 (52.294347, -1.532881): [7, 6.571428571428571],
 (52.293648, -1.535616): [13, 6.083333333333333],
 (52.290688, -1.533008): [8, 4.75],
 (52.28815, -1.534471): [71, 5.242857142857143],
 (52.291005, -1.538107): [75, 6.733333333333333],
 (52.290255, -1.537103): [47, 5.76595744680851],
 (52.292971, -1.532837): [10, 7.111111111111111],
 (52.293256, -1.534374): [35, 5.2],
 (52.292158, -1.567242): [12, 7.75],
 (52.291379, -1.565579): [4, 5.0],
 (52.291877, -1.5666): [35, 6.942857142857143],
 (52.290946, -1.565231): [4, 5.0],
 (52.290252, -1.564563): [11, 7.818181818181818],
 (52.294003, -1.567694): [14, 6.571428571428571],
 (52.291477, -1.548599): [17, 6.6875],
 (52.290978, -1.549763): [3, 5.333333333333333],
 (52.291579, -1.549244): [17, 6.6875],
 (52.285349, -1.533313): [83, 6.592592592592593],
 (52.291028, -1.541654): [28, 6.035714285714286],
 (52.289416, -1.545688): [3, 8.333333333333334],
 (52.292518, -1.555055): [10, 9.1],
 (52.294979, -1.545118): [10, 3.9],
 (52.292094, -1.545382): [2, 10.0],
 (52.292952, -1.528058): [12, 5.916666666666667],
 (52.288819, -1.530946): [2, 10.0],
 (52.293158, -1.525475): [5, 7.0],
 (52.292723, -1.524717): [10, 6.3],
 (52.287252, -1.508165): [2, 8.5],
 (52.293621, -1.524458): [9, 5.555555555555555],
 (52.278124, -1.516064): [9, 7.777777777777778],
 (52.278402, -1.511635): [6, 5.833333333333333],
 (52.278413, -1.50992): [9, 10.0],
 (52.277995, -1.513193): [3, 7.333333333333333],
 (52.286324, -1.531866): [11, 5.7],
 (52.284536, -1.520993): [23, 2.8260869565217392],
 (52.285854, -1.52007): [15, 5.6],
 (52.28489, -1.517442): [16, 7.1875],
 (52.281128, -1.51867): [71, 7.816901408450704],
 (52.268687, -1.543892): [6, 6.833333333333333],
 (52.281516, -1.565323): [6, 7.5],
 (52.287267, -1.569489): [3, 5.0],
 (52.283262, -1.558592): [4, 6.25],
 (52.282623, -1.548807): [26, 2.5],
 (52.287406, -1.568124): [5, 4.8],
 (52.279098, -1.532558): [4, 4.75],
 (52.277069, -1.528783): [17, 6.0625],
 (52.276334, -1.531634): [6, 6.666666666666667],
 (52.278187, -1.52732): [14, 6.285714285714286],
 (52.280056, -1.524662): [2, 3.0],
 (52.277542, -1.527737): [5, 7.2],
 (52.27511, -1.522282): [10, 9.4],
 (52.274977, -1.524877): [3, 7.333333333333333],
 (52.274694, -1.526068): [9, 7.444444444444445],
 (52.284756, -1.547246): [12, 4.416666666666667],
 (52.279459, -1.539736): [4, 4.75],
 (52.283322, -1.529934): [28, 6.2592592592592595],
 (52.283517, -1.533801): [54, 6.648148148148148],
 (52.283434, -1.531017): [34, 5.470588235294118],
 (52.271201, -1.522573): [6, 5.166666666666667],
 (52.274777, -1.513433): [2, 7.0],
 (52.27042, -1.52072): [5, 5.4],
 (52.27274, -1.512005): [8, 8.0],
 (52.272713, -1.532024): [2, 1.5],
 (52.290652, -1.537377): [44, 6.0227272727272725],
 (52.292845, -1.532619): [6, 4.8],
 (52.293753, -1.537242): [33, 5.696969696969697],
 (52.291245, -1.537444): [56, 6.660714285714286],
 (52.294832, -1.53726): [6, 5.5],
 (52.293315, -1.533405): [9, 7.222222222222222],
 (52.294952, -1.569019): [4, 7.0],
 (52.290155, -1.56779): [3, 6.333333333333333],
 (52.29338, -1.569445): [41, 5.7073170731707314],
 (52.292261, -1.54909): [12, 6.0],
 (52.290172, -1.543423): [8, 6.125],
 (52.290876, -1.54409): [3, 6.333333333333333],
 (52.287248, -1.538234): [16, 6.6875],
 (52.293919, -1.552328): [6, 7.5],
 (52.287433, -1.553596): [12, 6.25],
 (52.287557, -1.55314): [12, 6.25],
 (52.291701, -1.55301): [14, 5.642857142857143],
 (52.292586, -1.539952): [5, 5.6],
 (52.294204, -1.540024): [2, 4.0],
 (52.291416, -1.521696): [10, 5.111111111111111],
 (52.291224, -1.529879): [11, 7.363636363636363],
 (52.290999, -1.529647): [11, 7.363636363636363],
 (52.277687, -1.51475): [13, 6.769230769230769],
 (52.278211, -1.519845): [3, 7.0],
 (52.280962, -1.511123): [12, 7.083333333333333],
 (52.279967, -1.509624): [6, 10.0],
 (52.276212, -1.510325): [5, 6.4],
 (52.276103, -1.510136): [5, 6.4],
 (52.286648, -1.523037): [12, 5.454545454545454],
 (52.283424, -1.528305): [7, 6.428571428571429],
 (52.286368, -1.518379): [13, 6.230769230769231],
 (52.282112, -1.554104): [1, 5.0],
 (52.268888, -1.547246): [9, 8.777777777777779],
 (52.274285, -1.547865): [2, 7.0],
 (52.273547, -1.550013): [5, 5.2],
 (52.27392, -1.546594): [2, 4.5],
 (52.275639, -1.563768): [4, 4.25],
 (52.279698, -1.536451): [3, 4.333333333333333],
 (52.277624, -1.539594): [2, 10.0],
 (52.273771, -1.533654): [33, 5.2727272727272725],
 (52.273806, -1.522237): [17, 6.411764705882353],
 (52.273175, -1.521746): [8, 8.125],
 (52.281284, -1.544408): [13, 4.6923076923076925],
 (52.280479, -1.538421): [3, 6.333333333333333],
 (52.280545, -1.532469): [9, 4.444444444444445],
 (52.279808, -1.53255): [7, 8.571428571428571],
 (52.282538, -1.53173): [2, 4.5],
 (52.283858, -1.533637): [54, 6.648148148148148],
 (52.275409, -1.513851): [4, 5.25],
 (52.269999, -1.518966): [1, 5.0],
 (52.275037, -1.510939): [5, 4.8],
 (52.273519, -1.513491): [1, 7.0],
 (52.270464, -1.533982): [4, 2.0],
 (52.269569, -1.528086): [11, 4.545454545454546],
 (52.278539, -1.501358): [1, 5.0],
 (52.294541, -1.529727): [40, 5.625],
 (52.294317, -1.534289): [9, 7.333333333333333],
 (52.290731, -1.539238): [22, 5.9523809523809526],
 (52.289129, -1.538801): [15, 5.714285714285714],
 (52.288535, -1.564624): [11, 7.818181818181818],
 (52.291219, -1.561123): [7, 7.666666666666667],
 (52.292917, -1.546503): [5, 4.4],
 (52.292396, -1.542066): [10, 7.666666666666667],
 (52.286937, -1.541462): [7, 9.5],
 (52.286813, -1.54205): [7, 9.5],
 (52.294357, -1.556503): [1, 5.0],
 (52.291725, -1.55474): [4, 7.5],
 (52.289022, -1.557875): [4, 7.0],
 (52.281737, -1.509384): [5, 4.0],
 (52.28148, -1.508156): [3, 3.3333333333333335],
 (52.282025, -1.507344): [1, 10.0],
 (52.287006, -1.52038): [2, 2.0],
 (52.284375, -1.518987): [5, 5.2],
 (52.28643, -1.520284): [9, 5.222222222222222],
 (52.284092, -1.520133): [17, 7.411764705882353],
 (52.280763, -1.558617): [5, 4.75],
 (52.271642, -1.555044): [5, 3.4],
 (52.269767, -1.542035): [8, 8.875],
 (52.287563, -1.566833): [9, 6.222222222222222],
 (52.275328, -1.52269): [10, 9.4],
 (52.282632, -1.530571): [9, 4.555555555555555],
 (52.272385, -1.521871): [6, 5.166666666666667],
 (52.268745, -1.528886): [6, 6.333333333333333],
 (52.272168, -1.49781): [1, 10.0],
 (52.289472, -1.536964): [2, 10.0],
 (52.290563, -1.539988): [13, 6.833333333333333],
 (52.289757, -1.543222): [8, 6.125],
 (52.290648, -1.541057): [28, 6.035714285714286],
 (52.293717, -1.544222): [9, 6.111111111111111],
 (52.29247, -1.540276): [5, 5.6],
 (52.293836, -1.524119): [9, 5.555555555555555],
 (52.277779, -1.515423): [17, 7.235294117647059],
 (52.287104, -1.52466): [7, 5.857142857142857],
 (52.275135, -1.568493): [3, 5.666666666666667],
 (52.281355, -1.563111): [4, 3.5],
 (52.280783, -1.559277): [5, 4.75],
 (52.285023, -1.568147): [1, 5.0],
 (52.282384, -1.561899): [2, 10.0],
 (52.276657, -1.533712): [5, 5.4],
 (52.279907, -1.52802): [34, 6.176470588235294],
 (52.274711, -1.523664): [12, 4.916666666666667],
 (52.282358, -1.545526): [1, 1.0],
 (52.268992, -1.521058): [7, 7.285714285714286],
 (52.270419, -1.529425): [1, 5.0],
 (52.274008, -1.510027): [4, 4.75],
 (52.271341, -1.533035): [3, 4.0],
 (52.29282, -1.544744): [4, 3.25],
 (52.293088, -1.525974): [8, 6.875],
 (52.277683, -1.518326): [1, 4.0],
 (52.277961, -1.511376): [6, 5.833333333333333],
 (52.277569, -1.510222): [5, 8.5],
 (52.275754, -1.512484): [11, 4.909090909090909],
 (52.284872, -1.530753): [54, 6.296296296296297],
 (52.269278, -1.541073): [3, 10.0],
 (52.28459, -1.570057): [1, 4.0],
 (52.274149, -1.522453): [17, 6.411764705882353],
 (52.268784, -1.520738): [7, 7.285714285714286],
 (52.274202, -1.513439): [3, 5.333333333333333],

Defines the weightings used to find the safety score.

In [108]:
# Original weights based on percentages
survey_weightings = {
    "crime": 95.9,
    "public_space": (75 + 83.3) / 2,  
    "emergency": 80.2,
    "crowded": 78.2,
    "lighting": 85.4,
    "pos_keywords": 10, # Gave a percentage of 10 to start with. 
    "neg_keywords": -10 # Gave a percentage of 10 to start with. 
}

# Sum of the original weights
total_weight = sum(survey_weightings.values())

# Normalize each weight
normalized_weights = {k: v / total_weight for k, v in survey_weightings.items()}

print(normalized_weights)

{'crime': 0.2289602482989137, 'public_space': 0.18896979825713262, 'emergency': 0.19147666228960247, 'crowded': 0.18670168318013608, 'lighting': 0.20389160797421513, 'pos_keywords': 0.02387489554733198, 'neg_keywords': -0.02387489554733198}

In [109]:
# Function to calculate the safety score of a particular coordinate
def calculate_safety_score(max_crime, num_crime, space_rating, emergency_rating, crowd_rating, 
                           unlit_rating, severity, weightings, keywords, pos_keywords, neg_keywords):
    
    safety_score = 0

    if num_crime > 0:
        safety_score += ((max_crime - num_crime) / max_crime) * weightings["crime"] * ((10 - severity) / 10)
    else:
        safety_score += weightings["crime"]

    # Public space score calculation
    if space_rating > 0:
        safety_score += (space_rating * weightings["public_space"])
    else: 
        safety_score -= weightings["public_space"]
    
    if emergency_rating > 0:
        safety_score += (emergency_rating * weightings["emergency"])
    else: 
        safety_score -= weightings["emergency"]

    if crowd_rating > 0:
        safety_score += (crowd_rating * weightings["crowded"])
    else: 
        safety_score -= weightings["crowded"]

    if unlit_rating > 0:
        safety_score += (unlit_rating * weightings["lighting"])
    else: 
        safety_score -= weightings["lighting"]

    pos_count = sum(keywords.count(word) for word in pos_keywords)
    neg_count = sum(keywords.count(word) for word in neg_keywords)

    total_keywords = pos_count + neg_count

    if total_keywords > 0:
        pos_ratio = pos_count / total_keywords
        neg_ratio = neg_count / total_keywords
        safety_score += (pos_ratio * weightings["pos_keywords"]) + (neg_ratio * weightings["neg_keywords"])
        
    return safety_score

In [ ]:
def get_safety_scores(coords, max_crime, num_crime, space_rating, emergency_rating, 
                      crowd_rating, unlit_rating, severity, weightings, keywords, pos_keywords, 
                      neg_keywords, year, output_file):
    safety_scores = []
    for coordinate, (crime_num, severity) in coords.items():
        lat = coordinate[0]
        lon = coordinate[1]

        safety_score = calculate_safety_score(max_crime, num_crime, space_rating, emergency_rating, 
                                              crowd_rating, unlit_rating, severity, weightings, keywords, 
                                              pos_keywords, neg_keywords)
        
        safety_scores.append({
            "Latitude": lat,
            "Longitude": lon,
            "Safety Score": safety_score,
            "Year": year
        })

    safety_df = pd.DataFrame(safety_scores)
    existing_df = pd.read_csv(output_file)
    joined_df = pd.concat([existing_df, safety_df], ignore_index=True)
    joined_df.to_csv(output_file, index=False)

Removing repetition - Max_sum similarity and Maximal Marginal Relevance.

In [83]:
# keywords = model.extract_keywords(doc)
# model.extract_keywords(doc, keyphrase_ngram_range=(1,3), stop_words='english',
#                        use_maxsum=True, nr_candidates=20, top_n=4)
# model.extract_keywords(doc, keyphrase_ngram_range=(1,3), stop_words='english',
#                        use_mmr=True, diversity=0.9)